### ISSUE TITLE
Air ventilation system WRG KOMFORT EC DBE 550 L S21 and others

### ISSUE THREAD

**Issue by toralt** [PaulMT/homebridge-blauberg-vento#1]
Just wanna let you know, also the centralized air ventilation system WRG Komfort is working with your Plugin. 
As you said, on/off and the 3 steps for ventilation power (1, 2, 3) are working. 
Great, Thanks for that!

**Comment by PaulMT** [comment]
Nice to hear that.
I've released new version, hope it will still work fine for you.

**Comment by toralt** [comment]
I tested it but for my Blauberg WRG it does not work perfectly. I get about 2 hours after starting the plugin many errors which I do not get with 0.5.3 Not sure what my issue is but I guess it has something todo with my WRG system with maybe has a little different API or maybe way more Options as the Vento.


![plugin_error](https://user-images.githubusercontent.com/55451293/215844301-f4581ab4-6504-4d6e-bcb1-c08278b44870.png)

**Comment by PaulMT** [comment]
There was a bug with these timeouts. I've fixed it in 0.7.2

**Comment by toralt** [comment]
perfect, thank you!
