### ISSUE TITLE
Add "Ventilation Mode"

### ISSUE THREAD

**Issue by intellicasa** [PaulMT/homebridge-blauberg-vento#3]
Currently it's only possible to turn the vent on/off and to control the speed in 3 steps, but it's not possible to tell the vent if it should work in one of the 3 modes (ventilation, heat recovery, supply)

According to the Blauberg documentation, there is a parameter  #183/0x00B7 by which the mode can be controlled:

![image](https://github.com/PaulMT/homebridge-blauberg-vento/assets/35558932/c13d9505-9967-4251-a407-867359df2e69)

**Comment by mbjedk** [comment]
Perhaps a combination of [rotation direction](https://developers.homebridge.io/#/characteristic/RotationDirection) and [swing mode](https://developers.homebridge.io/#/characteristic/SwingMode), would make sense as equivalent HomeKit-controls?

**Comment by peoples0815** [comment]
Hi, @PaulMT,

could you please merge the Pull-Request if it is working?
To get the swingmode working?

**Comment by PaulMT** [comment]
Hi guys,

Sorry, I didn't had a time to look to this project.
I've already added this feature and testing it locally. I will try to release it this week (maybe tomorrow).

**Comment by PaulMT** [comment]
Version 0.9.0 released. Let me know if you have some problems

**Comment by cscholz** [comment]
> Version 0.9.0 released. Let me know if you have some problems

Update and working like a charm with Vento A30, A50 and Duo. Thank you very much!
